/**
 * Baked intent-learning seed: a release-time snapshot of validated
 * businesses/{id}/intentLearnings rows, shipped inside the Docker image as
 * backend/src/data/intentLearnings.seed.json (generated by
 * src/scripts/exportIntentLearningsSeed.js).
 *
 * Decision doc: whatorder-vault/Intelligence/decisions/2026-07-14-intent-learnings-release-seed.md
 *
 * Kill switch: INTENT_SEED_DISABLED=1 disables the layer without a redeploy.
 */

let seedOverride;

function loadSeedFile() {
  try {
    // eslint-disable-next-line global-require
    return require('../data/intentLearnings.seed.json');
  } catch {
    return null;
  }
}

let seedCache = null;
let seedLoaded = false;

function getSeed() {
  if (seedOverride !== undefined) return seedOverride;
  if (!seedLoaded) {
    seedCache = loadSeedFile();
    seedLoaded = true;
  }
  return seedCache;
}

function seedEnabled() {
  return process.env.INTENT_SEED_DISABLED !== '1';
}

function seedRelease() {
  return getSeed()?.release ?? null;
}

/** @returns {Record<string, object>} textKey → seed entry (docId, items, …), or {} */
function seedEntriesForBusiness(businessId, { ignoreDisabled = false } = {}) {
  if (!businessId || (!ignoreDisabled && !seedEnabled())) return {};
  const entries = getSeed()?.businesses?.[businessId];
  return entries && typeof entries === 'object' ? entries : {};
}

/**
 * ignoreDisabled: override bookkeeping (corrections/deletions) must see the
 * seed even while INTENT_SEED_DISABLED=1, so re-enabling can't resurrect a
 * phrase the owner already fixed.
 */
function seedEntryForKey(businessId, textKey, { ignoreDisabled = false } = {}) {
  if (!textKey) return null;
  return seedEntriesForBusiness(businessId, { ignoreDisabled })[textKey] ?? null;
}

/** Test helper: inject a seed object (or null for "no seed file"). */
function _setSeedForTests(seed) {
  seedOverride = seed;
}

function _resetSeedForTests() {
  seedOverride = undefined;
  seedCache = null;
  seedLoaded = false;
}

module.exports = {
  seedEnabled,
  seedRelease,
  seedEntriesForBusiness,
  seedEntryForKey,
  _setSeedForTests,
  _resetSeedForTests,
};
